# Generated by Django 5.0.4 on 2024-04-25 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventLogger', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
